language: java

jdk:
  - oraclejdk8

script:
  - gradle build

notifications:
  email:
    recipients:
      - manuelf.mola@gmail.com
      - cmarting@gmail.com
    on_success: change
    on_failure: always
