logging:
  level:
    com.example: DEBUG

foo:
    enabled: false
    remote-address: 192.168.1.1
    security:
        username: foo
        password: myPassword
        roles:
          - USER
          - ADMIN